#pragma once

#define SIRIUS_VERSION_MAJOR 8
#define SIRIUS_VERSION_MINOR 0

#define STRINGIFY2(x) #x
#define STRINGIFY(x) STRINGIFY2(x)

#define SIRIUS_VERSION_STRING STRINGIFY(SIRIUS_VERSION_MAJOR) "." STRINGIFY(SIRIUS_VERSION_MINOR)

static constexpr int BENCH_DEPTH = 14;
